### ISSUE TITLE
What bootscript or base image?

### ISSUE THREAD

**Issue by xtagon** [edouardb/kubernetes-terraform-scaleway#2]
Hi,

Just wondering.... what bootscript and base image correspond to the GUIDs in the default vars file? Is there a way to get all available base image IDs from Scaleway?

Thanks,

Justin

**Comment by edouardb** [comment]
Hello @xtagon ,

You can get them via the following endpoint: api-marketplace.scaleway.com/images

**Comment by xtagon** [comment]
Thanks @edouardb 👍
